import { Button } from "primereact/button";

export default function Footer() {
  return (
    <footer className="bg-gray-100 text-black opacity-50 mt-9">
      <div className="max-w-7xl mx-auto  py-4">
        {/* Disclaimer */}
        <p className="text-sm leading-relaxed  ">
          <span className="font-bold text-black text-xl">Disclaimer:</span>{" "}
          Floor Plan Automation is an AI-powered platform designed to assist
          HVAC and MEP professionals with takeoff and estimation
          workflows.Results generated by the system should be reviewed and
          validated by qualified professionals before use in construction or
          bidding decisions.
        </p>

        <div className="flex gap-3 pl-125">
          <Button
            icon="pi pi-globe"
            className="p-button-text p-button-rounded text-gray-300 hover:text-white"
            onClick={() => window.open("https://saazvat.com/", "_blank")}
            tooltip="Official Website"
          />

          <Button
            icon="pi pi-linkedin"
            className="p-button-text p-button-rounded text-gray-300 hover:text-white"
            onClick={() =>
              window.open(
                "https://in.linkedin.com/company/saazvat-technologies",
                "_blank",
              )
            }
            tooltip="LinkedIn"
          />

          <Button
            icon="pi pi-youtube"
            className="p-button-text p-button-rounded text-gray-300 hover:text-white"
            onClick={() =>
              window.open(
                "https://www.youtube.com/channel/UCc5g3zVVavUJjuRjUbDqW5Q",
                "_blank",
              )
            }
            tooltip="YouTube"
          />
        </div>

        {/* Bottom Row */}
        <div className="flex flex-col md:flex-row justify-between gap-6">
          {/* Copyright */}
          <p className="text-sm text-black-400 pl-110 items-center">
            © {new Date().getFullYear()} Floor Plan Automation. All rights
            reserved.
          </p>

          {/* Social / Links */}
        </div>
      </div>
    </footer>
  );
}
